# Generated by Django 5.0.2 on 2024-02-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cab',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
