# Generated by Django 5.0.2 on 2024-02-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
